### ISSUE TITLE
Fixed guzzle version

### ISSUE THREAD

**Issue by bernhardh** [quickscraper/quickscraper-sdk-php#16]
Could the guzzle version not be restricted so much? You have set it to the fixed version `7.0.0` which is really weird since current version is `7.8.1` and make problems, when you already have other packages using guzzle. 

I would suggest to use `^7.0` instead.

**Comment by quickscraper** [comment]
Hi @bernhardh ,

Thank you for bringing this to my attention and providing your suggestion. I appreciate your input. I have made the necessary changes, and the Guzzle version is now set to latest version in the project.

Feel free to test it out, and if you encounter any further issues or have additional feedback, please let me know.

Thank you,
Team QuickScraper.
